# Generated by Django 5.2.7 on 2025-11-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('condition', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
    ]
