# Generated by Django 5.2.7 on 2025-11-12 19:35

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.upload_image)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('condition', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
    ]
