# Generated by Django 5.2.7 on 2025-11-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'managed': False},
        ),
    ]
