# Generated by Django 5.2.7 on 2025-11-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gallery',
            table='gallery',
        ),
    ]
