# Generated by Django 5.2.7 on 2025-11-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
