# Generated by Django 5.2.7 on 2025-11-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_facebook_team_instagram_team_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
