# Generated by Django 5.2.7 on 2025-10-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('page_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'page',
                'managed': False,
            },
        ),
    ]
