# Generated by Django 5.2.7 on 2025-10-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('youtubelink', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('feature', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
    ]
