# Generated by Django 5.2.7 on 2025-10-27 16:21

from django.db import migrations, models
import banner.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=banner.models.upload_image)),
                ('heading', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'banner'
            },
        ),
    ]
